#ifndef MESSAGE_LIB_GLOBAL_H
#define MESSAGE_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MESSAGE_LIB_LIBRARY)
#  define MESSAGE_LIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MESSAGE_LIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MESSAGE_LIB_GLOBAL_H
